src/Entity/Item.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 */
class Item
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $item_name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ItemList", inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $list;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $placement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getItemName(): ?string
    {
        return $this->item_name;
    }

    public function setItemName(string $item_name): self
    {
        $this->item_name = $item_name;

        return $this;
    }

    public function getList(): ?ItemList
    {
        return $this->list;
    }

    public function setList(?ItemList $list): self
    {
        $this->list = $list;

        return $this;
    }

    public function getColorCode(): ?string
    {
        return $this->color_code;
    }

    public function setColorCode(?string $color_code): self
    {
        $this->color_code = $color_code;

        return $this;
    }

    public function getPlacement(): ?string
    {
        return $this->placement;
    }

    public function setPlacement(?string $placement): self
    {
        $this->placement = $placement;

        return $this;
    }
}

src/Entity/ItemList.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemListRepository")
 */
class ItemList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="itemLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Item", mappedBy="list", orphanRemoval=true)
     */
    private $items;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Priority", inversedBy="item_lists")
     */
    private $priorities;

    

    public function __construct()
    {
        $this->items = new ArrayCollection();
        $this->priorities = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setList($this);
        }

        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->items->contains($item)) {
            $this->items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getList() === $this) {
                $item->setList(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Priority[]
     */
    public function getPriorities(): Collection
    {
        return $this->priorities;
    }

    public function addPriority(Priority $priority): self
    {
        if (!$this->priorities->contains($priority)) {
            $this->priorities[] = $priority;
        }

        return $this;
    }

    public function removePriority(Priority $priority): self
    {
        if ($this->priorities->contains($priority)) {
            $this->priorities->removeElement($priority);
        }

        return $this;
    }    
}

src/Form/ItemListType.php
<?php

namespace App\Form;

use App\Entity\ItemList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class ItemListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title',null,[
                    'label' => 'List name',
                    'attr' => ['class' => 'form-control']
                ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ItemList::class,
        ]);
    }
}

src/Controller/ItemListsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\ItemList;
use App\Entity\Item;
use App\Form\ItemListType;
use App\Form\ItemType;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\ItemListRepository;
use Doctrine\Common\Persistence\ObjectManager;
// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;


class ItemListsController extends AbstractController
{
     /**
     * @Route("user/lists", name="user_listing")
     */
    public function index( UserInterface $user, Request $request, PaginatorInterface $paginator )
    {
    	ini_set('memory_limit', -1);

    	$user_id = $user->getId();
    	$limit = $this->getParameter('knp_paginator.page_range');
    	
    	$item_list = new ItemList();
    	$form = $this->createForm(ItemListType::class, $item_list);

        $item = new Item();
        $form2 = $this->createForm(ItemType::class, $item);

     	// Retrieve the entity manager of Doctrine
        $entityManager = $this->getDoctrine()->getManager();
        
        // Get some repository of data, in our case we have an Appointments entity
        $listsRepository = $entityManager->getRepository(ItemList::class);
                
        // Find all the data on the Appointments table, filter your query as you need
        $listQuery = $listsRepository->createQueryBuilder('l')
            ->where('l.user= :user_id')
            ->setParameter('user_id', $user_id)
            ->getQuery();
        
        // Paginate the results of the query
        $my_list = $paginator->paginate(
            // Doctrine Query, not results
            $listQuery,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            $limit
        );        

        return $this->render('item_lists/index.html.twig', [
           'form' => $form->createView(),
           'my_list' => $my_list,
           'form2' => $form2->createView()
        ]);
    }

     /**
     * @Route("user/list_save", name="list_save", methods={"POST"}) 
     */
    public function save( UserInterface $user, Request $request, ItemListRepository $repository, ObjectManager $manager )
    {      	
        // Only include it if the function is reserved for ajax calls only.
        if (!$request->isXmlHttpRequest()) {
            return new JsonResponse(array(
                'status' => 'Error',
                'message' => 'Error'),
            400);
        }

    	if(isset($request->request))
    	{
    		$postData =  $request->get('item_list'); 
    		$user_id = $user->getId();

            // Check if record exists or not in db with same title and of same user
			$db_record = $repository->findOneByUserIdAndTitle($user_id,$postData['title']);
			    
            if ($db_record === null)
            { 
            	$item_list = new ItemList();
            	$item_list->setTitle($postData['title']);
            	$item_list->setUser($user);

            	$manager = $this->getDoctrine()->getManager();
                $manager->persist($item_list);

                $manager->flush();

            	return new JsonResponse(array(
            		'status' => 'Success',
            		'message' => 'List title saved in database successfully'),
            	200);
            }
            else
            {            	 
            	return new JsonResponse(array(
            		'status' => 'Error',
            		'message' => 'Title already exists in database'),
            	200);
            }
        }

        // If we reach this point, it means that something went wrong
        return new JsonResponse(array(
            'status' => 'Error',
            'message' => 'Error'),
        400);
    }


     /**
     * @Route("user/list_delete/{id}", name="list_delete", methods={"GET"}) 
     */
    public function delete( $id )
    {
    	$repository = $this->getDoctrine()->getRepository(ItemList::class);
    	$item_list = $repository->find($id);
        $em = $this->getDoctrine()->getManager();
		$em->remove($item_list);
		 
		$em->flush(); 

		$this->addFlash('success', "Item's list deleted successfully");
		return $this->redirectToRoute('user_listing');

    }
}

templates/item_lists/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item List{% endblock %}

{% block body %}
<div class="container mt-4">
	{% for message in app.flashes('success') %}
	<div class="row">
		<div class="col-md-12 col-12 mb-4">		
            <div class="alert alert-success">
            	{{ message }}
            </div>
                       
        </div>
	</div>
	{% endfor %}
	<div class="row">
		<div class="col-md-6 col-12 mb-4">
			<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add List</button>
		</div>
		<div class="col-md-6 col-12">
			<b>Total Records:</b> {{ my_list.getTotalItemCount }}
		</div>
	</div>
	<div class="row">
		{% for mlist in my_list %}
		<div class="col-md-6 col-12">
			<table class="table table-bordered" width="100%">
			    <tr>
			        {# sorting of properties based on query components #}
			        <th width="80%">{{ mlist.title }}</th>
			        <th>
			        	<a href="javascript:void(0)" onclick="deleteList('{{ mlist.id }}')"><i class="fa fa-times" aria-hidden="true" style="font-size:20px; color:red;"></i></a>
			        </th>
			    </tr>
			    {% if mlist.items %}
			    	{% for item in mlist.items %}
			    		<tr>
			        		<td colspan="2">
			        			<div class="row">
			        				<div class="col-md-9">
			        					<span style="color:{{item.ColorCode}};">{{ item.itemName }}
			        					<a href="javascript:void(0)" onclick="deleteItem('{{  item.id }}')"><i class="fa fa-times" aria-hidden="true"></i></a>
			        				</div>
			        			</div>
			        		</td>
			        	</tr>
				    {% endfor %}
				{% endif %}
				<tr>
					<td align="right" colspan="2"><a href="javascript:void(0);" data-id="{{ mlist.id }}" data-toggle="modal" data-target="#myModal2" class="add-item">Add Item <i class="fa fa-plus-square" aria-hidden="true"></i></a></td>
				</tr>			        
			</table>
		</div>
		{% endfor %}
	</div>
	<div class="row">
		<div class="col-md-12 col-12">
			{# display navigation #}
			<div class="navigation">
			    {{ knp_pagination_render(my_list) }}
			</div>
		</div>
	</div>   
</div>
<!-- The Modal -->
<div class="modal" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">		

			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">New List</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			{{ form_start(form, {'action': path('list_save'), 'method': 'POST', 'attr': {'id':'item_list'}}) }}

			<!-- Modal body -->
			<div class="modal-body">
				<div id="success_message" style="display:none" class="alert alert-success"></div>
				<div id="error_message" style="display:none" class="alert alert-danger"></div>
				<div class="row">
					<div class="col-lg-5">
						{{ form_label(form.title) }}
					</div>
					<div class="col-lg-7">
						<div class="form-group">
							{{ form_widget(form.title) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							<button type="button" class="btn btn-info btn-lg" onclick="submitList();">Add List</button> 
						</div>
					</div>
				</div>
			</div> 
			{{ form_end(form) }}

			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
			</div>

		</div>
	</div>
</div>

<!-- The Modal -->
<div class="modal" id="myModal2">
	<div class="modal-dialog">
		<div class="modal-content">		

			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">New Item</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			{{ form_start(form2, {'action': path('item_save'), 'method': 'POST', 'attr': {'id':'item_save'}}) }}				
				{{ form_widget(form2.list_id) }}
			<!-- Modal body -->
			<div class="modal-body">
				<div id="success_item_message" style="display:none" class="alert alert-success"></div>
				<div id="error_item_message" style="display:none" class="alert alert-danger"></div>
				<div class="row">
					<div class="col-lg-5">
						{{ form_label(form2.item_name) }}
					</div>
					<div class="col-lg-7">
						<div class="form-group">
							{{ form_widget(form2.item_name) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-5">
						Placement of the item
					</div>
					<div class="col-lg-7">
						<div class="form-group">
							{{ form_widget(form2.placement,{ 'separator': '<br />' }) }}
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-5">
						{{ form_label(form2.color_code) }}
					</div>
					<div class="col-lg-7">
						<div class="form-group">
							{{ form_widget(form2.color_code) }}
						</div>
					</div>
				</div>				
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							<button type="button" class="btn btn-info btn-lg" onclick="submitItem();">Add Item</button> 
						</div>
					</div>
				</div>
			</div>
			{{ form_end(form2) }}

			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
			</div>

		</div>
	</div>
</div>
{% endblock %}

{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" type="text/javascript"></script>
<script src="/js/evol-colorpicker.min.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
$(document).ready(function(){
	// Change theme
    $('.css').on('click', function(evt){
        var theme=this.innerHTML.toLowerCase().replace(' ', '-'),
            url='http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/'+theme+'/jquery-ui.css';
        $('#jquiCSS').attr('href', url);
        $('.css').removeClass('sel');
        $(this).addClass('sel');
    });

	$('#item_color_code').colorpicker({showOn:'focus'});

	$('.add-item').on( 'click', function(){
		$('#item_list_id').val($(this).attr("data-id"));
	});	
});

function submitList(){
	 
	form = $('#item_list').serialize();

	$.post("{{ path('list_save') }}", form, function(result){
		if(result.status == 'Success'){
			$('#success_message').html(result.message).show();			 
		}else{
			$('#error_message').html(result.message).show();
		}

		setTimeout(function(){
			if(result.status == 'Success'){
				document.location.reload();
			}else{
				$('#error_message').html('').hide();
			}
		}, 3000);
	});	 
}

function submitItem(){
	 
	form = $('#item_save').serialize();

	$.post("{{ path('item_save') }}", form, function(result){
		if(result.status == 'Success'){
			$('#success_item_message').html(result.message).show();
			 
		}else{
			$('#error_item_message').html(result.message).show();
		}

		setTimeout(function(){
			if(result.status == 'Success'){
				document.location.reload();
			}else{
				$('#error_item_message').html('').hide();
			}
		}, 3000);
	});
}

function deleteList(list_id) {
    if (confirm("Are you sure you want to delete this list?")) {
    	var url = "/user/list_delete/" + list_id;
    	document.location.href = url;
    }
    return false;
}

function deleteItem(item_id) {
    if (confirm("Are you sure you want to delete this item?")) {
    	var url = "/user/item_delete/" + item_id;
    	document.location.href = url;
    }
    return false;
}
</script>
{% endblock %}
{% block style %}
<style type="text/css">
#item_placement label{
	width:90%;
	display: inline-block;
}
#item_placement input{
	width:10%;
	display: inline-block;
}
.evo-cp-wrap{
	width: 100% !important;
}
</style>
{% endblock %}
{% block stylesheets %}
<link id="jquiCSS" rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css" type="text/css" media="all">
<link href="/css/demo.css" rel="stylesheet" /> 
<link href="/css/evol-colorpicker.min.css" rel="stylesheet" />
{% endblock %}